

---


**RA2011003010488**

**Mohammed Irfan M A**

**Numpy Operations**

---



In [ ]:
import numpy as np
a1 = [1,2,3,4]
a2 = [2,4,6,8]
a3=np.add(a1,a2)
print(np.array(a3))

[ 3  6  9 12]


In [ ]:
a4=np.subtract(a3,a2)
print(a4)

[1 2 3 4]


In [ ]:
a5=np.multiply(a1,a2)
print(a5)

[ 2  8 18 32]


In [ ]:
a6 = np.divide(a2,a1)
print(a6)

[2. 2. 2. 2.]


In [ ]:
a7 = np.exp(a1)
print(a7)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
a8 = np.sqrt(a2)
print(a8)

[1.41421356 2.         2.44948974 2.82842712]


In [ ]:
np.array_equal(a1,a2)

False

In [ ]:
np.copy(a1)

array([1, 2, 3, 4])

In [ ]:
 np.sort(a3)

array([ 3,  6,  9, 12])

In [ ]:
a10 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = a10.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
np.append(a1,10)

array([ 1,  2,  3,  4, 10])

In [ ]:
np.delete(a1,2,axis=0) 

array([1, 2, 4])

In [ ]:
np.concatenate((a1,a2))

array([1, 2, 3, 4, 2, 4, 6, 8])

In [ ]:
a11 = np.array([1, 2, 3, 4, 5, 6])

newarr1 = np.array_split(a11, 3)

print(newarr1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
a12 = np.array([1, 2, 3, 4, 5, 6, 7])

print(a12[1:5])

[2 3 4 5]
